/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SavedLooksRouteImport } from './routes/saved-looks'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ApiBootstrapSecretsRouteImport } from './routes/api/bootstrap-secrets'
import { Route as ApiProductRecommendationsRouteImport } from './routes/api/product-recommendations'
import { Route as ApiStripeCheckoutRouteImport } from './routes/api/stripe-checkout'
import { Route as ApiStripeConfigRouteImport } from './routes/api/stripe-config'
import { Route as ApiStripeVerifySessionRouteImport } from './routes/api/stripe-verify-session'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe-webhook'
import { Route as ApiTryOnRouteImport } from './routes/api/try-on'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedLooksRoute = SavedLooksRouteImport.update({
  id: '/saved-looks',
  path: '/saved-looks',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBootstrapSecretsRoute = ApiBootstrapSecretsRouteImport.update({
  id: '/api/bootstrap-secrets',
  path: '/api/bootstrap-secrets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductRecommendationsRoute =
  ApiProductRecommendationsRouteImport.update({
    id: '/api/product-recommendations',
    path: '/api/product-recommendations',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiStripeCheckoutRoute = ApiStripeCheckoutRouteImport.update({
  id: '/api/stripe-checkout',
  path: '/api/stripe-checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeConfigRoute = ApiStripeConfigRouteImport.update({
  id: '/api/stripe-config',
  path: '/api/stripe-config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeVerifySessionRoute = ApiStripeVerifySessionRouteImport.update({
  id: '/api/stripe-verify-session',
  path: '/api/stripe-verify-session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe-webhook',
  path: '/api/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTryOnRoute = ApiTryOnRouteImport.update({
  id: '/api/try-on',
  path: '/api/try-on',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/saved-looks': typeof SavedLooksRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/studio': typeof StudioRoute
  '/terms': typeof TermsRoute
  '/api/bootstrap-secrets': typeof ApiBootstrapSecretsRoute
  '/api/product-recommendations': typeof ApiProductRecommendationsRoute
  '/api/stripe-checkout': typeof ApiStripeCheckoutRoute
  '/api/stripe-config': typeof ApiStripeConfigRoute
  '/api/stripe-verify-session': typeof ApiStripeVerifySessionRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/api/try-on': typeof ApiTryOnRoute
  '/auth/callback': typeof AuthCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/saved-looks': typeof SavedLooksRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/studio': typeof StudioRoute
  '/terms': typeof TermsRoute
  '/api/bootstrap-secrets': typeof ApiBootstrapSecretsRoute
  '/api/product-recommendations': typeof ApiProductRecommendationsRoute
  '/api/stripe-checkout': typeof ApiStripeCheckoutRoute
  '/api/stripe-config': typeof ApiStripeConfigRoute
  '/api/stripe-verify-session': typeof ApiStripeVerifySessionRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/api/try-on': typeof ApiTryOnRoute
  '/auth/callback': typeof AuthCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/saved-looks': typeof SavedLooksRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/studio': typeof StudioRoute
  '/terms': typeof TermsRoute
  '/api/bootstrap-secrets': typeof ApiBootstrapSecretsRoute
  '/api/product-recommendations': typeof ApiProductRecommendationsRoute
  '/api/stripe-checkout': typeof ApiStripeCheckoutRoute
  '/api/stripe-config': typeof ApiStripeConfigRoute
  '/api/stripe-verify-session': typeof ApiStripeVerifySessionRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/api/try-on': typeof ApiTryOnRoute
  '/auth/callback': typeof AuthCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/robots.txt'
    | '/saved-looks'
    | '/signup'
    | '/sitemap.xml'
    | '/studio'
    | '/terms'
    | '/api/bootstrap-secrets'
    | '/api/product-recommendations'
    | '/api/stripe-checkout'
    | '/api/stripe-config'
    | '/api/stripe-verify-session'
    | '/api/stripe-webhook'
    | '/api/try-on'
    | '/auth/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/robots.txt'
    | '/saved-looks'
    | '/signup'
    | '/sitemap.xml'
    | '/studio'
    | '/terms'
    | '/api/bootstrap-secrets'
    | '/api/product-recommendations'
    | '/api/stripe-checkout'
    | '/api/stripe-config'
    | '/api/stripe-verify-session'
    | '/api/stripe-webhook'
    | '/api/try-on'
    | '/auth/callback'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/robots.txt'
    | '/saved-looks'
    | '/signup'
    | '/sitemap.xml'
    | '/studio'
    | '/terms'
    | '/api/bootstrap-secrets'
    | '/api/product-recommendations'
    | '/api/stripe-checkout'
    | '/api/stripe-config'
    | '/api/stripe-verify-session'
    | '/api/stripe-webhook'
    | '/api/try-on'
    | '/auth/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SavedLooksRoute: typeof SavedLooksRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StudioRoute: typeof StudioRoute
  TermsRoute: typeof TermsRoute
  ApiBootstrapSecretsRoute: typeof ApiBootstrapSecretsRoute
  ApiProductRecommendationsRoute: typeof ApiProductRecommendationsRoute
  ApiStripeCheckoutRoute: typeof ApiStripeCheckoutRoute
  ApiStripeConfigRoute: typeof ApiStripeConfigRoute
  ApiStripeVerifySessionRoute: typeof ApiStripeVerifySessionRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  ApiTryOnRoute: typeof ApiTryOnRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved-looks': {
      id: '/saved-looks'
      path: '/saved-looks'
      fullPath: '/saved-looks'
      preLoaderRoute: typeof SavedLooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bootstrap-secrets': {
      id: '/api/bootstrap-secrets'
      path: '/api/bootstrap-secrets'
      fullPath: '/api/bootstrap-secrets'
      preLoaderRoute: typeof ApiBootstrapSecretsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/product-recommendations': {
      id: '/api/product-recommendations'
      path: '/api/product-recommendations'
      fullPath: '/api/product-recommendations'
      preLoaderRoute: typeof ApiProductRecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe-checkout': {
      id: '/api/stripe-checkout'
      path: '/api/stripe-checkout'
      fullPath: '/api/stripe-checkout'
      preLoaderRoute: typeof ApiStripeCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe-config': {
      id: '/api/stripe-config'
      path: '/api/stripe-config'
      fullPath: '/api/stripe-config'
      preLoaderRoute: typeof ApiStripeConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe-verify-session': {
      id: '/api/stripe-verify-session'
      path: '/api/stripe-verify-session'
      fullPath: '/api/stripe-verify-session'
      preLoaderRoute: typeof ApiStripeVerifySessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe-webhook': {
      id: '/api/stripe-webhook'
      path: '/api/stripe-webhook'
      fullPath: '/api/stripe-webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/try-on': {
      id: '/api/try-on'
      path: '/api/try-on'
      fullPath: '/api/try-on'
      preLoaderRoute: typeof ApiTryOnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SavedLooksRoute: SavedLooksRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StudioRoute: StudioRoute,
  TermsRoute: TermsRoute,
  ApiBootstrapSecretsRoute: ApiBootstrapSecretsRoute,
  ApiProductRecommendationsRoute: ApiProductRecommendationsRoute,
  ApiStripeCheckoutRoute: ApiStripeCheckoutRoute,
  ApiStripeConfigRoute: ApiStripeConfigRoute,
  ApiStripeVerifySessionRoute: ApiStripeVerifySessionRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  ApiTryOnRoute: ApiTryOnRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
